### PR TITLE
Fix auto update delivery list upon creating and update sales order wi…

### LINKED ISSUE #405: [Sales Order]: Creating sales order with delivery
After creating sales order with delivery we should automatically update the deliveries list without refreshing the deliveries page.

### PR DESCRIPTION
**Pull request by acerapa**
**Highlights**
- Automatically update the deliveries list when new sales order is created or updated

**Remarks**
- Done

### CODE REVIEW

File: frontend/src/stores/delivery.js [hunk 1]
```diff
@@ -56,6 +56,21 @@ export const useDeliveryStore = defineStore('delivery', () => {
...
+      if (index > -1) {
+        deliveries.value[index] = deliveryData
+      } else {
+        deliveries.value.unshift(deliveryData)
+      }
+    }
+  }
+
   // getters
   // TODO: Issue is that when creating a new sales order with delivery, it will not automatically fetched the deliveries
```
Comment (acerapa) [inline frontend/src/stores/delivery.js]: Remove comments

**Review by acerapa — COMMENTED** [review]
After request change, can already merge
